# This is the file used to maintain the Recruitment Poster.
---
#
# Here you can specify the output file
#
RSFilename : "RecruitmentSlide.pdf"
#
# You can change the font here. If is a custom font a
# modification to main.py is necessary. Two custom fonts
# are availabe: Trickster and Vampire. All common fonts
# should work
#
Font : 'Vampire'
FontSize : 28
FontColor : 'brickred'
# FontColor is currently not working. This must be changed in
# main.py. Search for TEXTCOLOR
#FontColor : 'brickred'
#
# I don't actually  know what this does yet lol
#
RSDocumentTitle : 'The Phant??m Alliance'
#
# This is the title that appears on the poster
#
RSTitle : 'Phantøm Alliance'
#
# This is where you put in your credentials to log
# in to the api
#
CredName : 'brianscotty'
CredPass : 'tz0tz1lSW'
CredNum : '123'
CredLet : 'abc'

SpreadsheetsID :
  Alliance Master: '1_uYgWWKUvJlP5rzq8JueYMgNYRamhF_kcl23dHwajBU'
  Rebellion: '1xGnx38jAuL0i1CZ8i2NgOpmZtUfo4tcB31QrHlAFNcI'
  Ørder: '1qjJmBY1K3BPrAH0gndS1GmcSkM8YSLwb3nuiK3eLU8o'
  Ëmpire: '1onscnyBzU4nGZVMyuwS3nsjwbr-UaFeEwiFrkcTguBQ'
  Havoc: '160FFse3fHpijJ5FcaKGacYLt0Bqnpkx_YoQmJ-cQSE4'
  Uprising: '1uMdcriSkqIPGJbqucVNr6YPG8mdaXJ7uXZ182i5NDPo'
  Lotus: '1lYeVaz_XxTFyCTK6MW4vk4ei5zACPTr8FYWBwA9xCws'
  Røgue: '1kcJxtkThpN9DnmQ3M_X-qSa5Vkn2kRDiou-Ke_u7btE'
  Away Team: '1petOJrvJnoQmPEXGI3dJmC2uMFwhI2VSU9YEYEnvQEk'
  Høpe: '1kj0zBkZf2LEGilyiZxiCSqTjX1gnKmQ0Bf9kUma8ucI'
  Beskar: '18wSBBzCsdWA_oXKZ3Aya--XfGpx_g7ExlixLpxoLOFk'
  Phøundlings: '1LZwZ2nwg4Vzy0h5QYkXIuLM3tfrp8OYi7syl2PBTTNI'
  Pain: '1aZprMd32Zxe-zl8yETSJDcEj56jSp6HZzQsnGPdtc0I'
  Death Watch: '1sy5jbViiYfmbdvJfN8VfgN27zXRgoO2PpssXoU5UoCw'
  Limb: '19uENg8bOd59fUHvFoCR-pOAMLg5sE792vk00PgY8B0I'

