# This is the file used to maintain the Recruitment Poster.
---
#
# Here you can specify the output file
#
RSFilename : "RecruitmentSlide.pdf"
#
# You can change the font here. If is a custom font a
# modification to main.py is necessary. Two custom fonts
# are availabe: Trickster and Vampire. All common fonts
# should work
#
Font : 'Vampire'
FontSize : 28
FontColor : 'brickred'
# FontColor is currently not working. This must be changed in
# main.py. Search for TEXTCOLOR
#FontColor : 'brickred'
#
# I don't actually  know what this does yet lol
#
RSDocumentTitle : 'The Phant??m Alliance'
#
# This is the title that appears on the poster
#
RSTitle : 'Phantøm Alliance'
#
# This is where you put in your credentials to log
# in to the api
#
CredName : 'brianscotty'
CredPass : 'tz0tz1lSW'
CredNum : '123'
CredLet : 'abc'

SpreadsheetsID : '14s5-_5BDiaYrzSqVeKX4vkkn4iBy8qxRm2P2ugFIUn4'

